package com.amster.db.hibernate;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableFileInfo generated by hbm2java
 */
public class TableFileInfo implements java.io.Serializable {

	private Integer id;
	private Boolean removeAllStacks;
	private String exceptionIgnoreList;
	private Integer fileInfo2logFile;

	public TableFileInfo() {
	}

	public TableFileInfo(Boolean removeAllStacks, String exceptionIgnoreList,
			Integer fileInfo2logFile) {
		this.removeAllStacks = removeAllStacks;
		this.exceptionIgnoreList = exceptionIgnoreList;
		this.fileInfo2logFile = fileInfo2logFile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getRemoveAllStacks() {
		return this.removeAllStacks;
	}

	public void setRemoveAllStacks(Boolean removeAllStacks) {
		this.removeAllStacks = removeAllStacks;
	}

	public String getExceptionIgnoreList() {
		return this.exceptionIgnoreList;
	}

	public void setExceptionIgnoreList(String exceptionIgnoreList) {
		this.exceptionIgnoreList = exceptionIgnoreList;
	}

	public Integer getFileInfo2logFile() {
		return this.fileInfo2logFile;
	}

	public void setFileInfo2logFile(Integer fileInfo2logFile) {
		this.fileInfo2logFile = fileInfo2logFile;
	}

}
