package com.amster.db.hibernate;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableDiagInfo generated by hbm2java
 */
public class TableDiagnostic implements java.io.Serializable {

	private Integer id;
	private String diagName;
	private Integer highWaterMark;
	private String highWaterTime;
	private Integer logFile;
	



	private Set<TableDiag> diags = new HashSet<TableDiag>(0);

	public TableDiagnostic() {
	}

	public TableDiagnostic(String diagName, Integer highWaterMark,
			String highWaterTime, Integer log_file) {
		this.diagName = diagName;
		this.highWaterMark = highWaterMark;
		this.highWaterTime = highWaterTime;
		this.logFile = log_file;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDiagName() {
		return this.diagName;
	}

	public void setDiagName(String diagName) {
		this.diagName = diagName;
	}

	public Integer getHighWaterMark() {
		return this.highWaterMark;
	}

	public void setHighWaterMark(Integer highWaterMark) {
		this.highWaterMark = highWaterMark;
	}

	public String getHighWaterTime() {
		return this.highWaterTime;
	}

	public void setHighWaterTime(String highWaterTime) {
		this.highWaterTime = highWaterTime;
	}

	public Integer getLogFile() {
		return logFile;
	}

	public void setLogFile(Integer logFile) {
		this.logFile = logFile;
	}
	
	public Set<TableDiag> getDiags() {
		return this.diags;
	}

	public void setDiags(Set<TableDiag> diags) {
		this.diags = diags;
	}

}
