package com.amster.db.hibernate;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableException generated by hbm2java
 */
public class TableException implements java.io.Serializable {

	private Integer id;
	private String exception;
	private String stackTrace;
	private Integer exceptionCount;
	@JsonIgnore
	private TableLogFile logFile;

	private Set<TableExceptionTimes> exceptionTimes = new HashSet<TableExceptionTimes>(0);

	public TableException() {
	}

	public TableException(String exception, String stackTrace,
			 Integer exceptionCount, TableLogFile log_file) {
		this.exception = exception;
		this.stackTrace = stackTrace;
		this.exceptionCount = exceptionCount;
		this.logFile = log_file;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getException() {
		return this.exception;
	}

	public void setException(String exception) {
		this.exception = exception;
	}

	public String getStackTrace() {
		return this.stackTrace;
	}

	public void setStackTrace(String stackTrace) {
		this.stackTrace = stackTrace;
	}


	public Integer getExceptionCount() {
		return this.exceptionCount;
	}

	public void setExceptionCount(Integer exceptionCount) {
		this.exceptionCount = exceptionCount;
	}

	public TableLogFile getLogFile(){
		return this.logFile;
	}
	
	public void setLogFile(TableLogFile log_file){
		this.logFile=log_file;
	}
	
	public Set<TableExceptionTimes> getExceptionTimes() {
		return this.exceptionTimes;
	}

	public void setExceptionTimes(Set<TableExceptionTimes> etimes) {
		this.exceptionTimes = etimes;
	}

}
