package com.amster.db.hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableTopQueries generated by hbm2java
 */

@Entity
@Table(name = "table_top_queries")
public class TableTopQueries implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "query_sql")
	private String querySql;
	
	@Column(name = "elapsed_time")
	private Float elapsedTime;
	
	@Column(name = "query_time")
	private String queryTime;
	
	@Column(name = "query_order")
	private Integer queryOrder;
	
	@JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "query2log_file")
	private TableLogFile logFile;

	public TableTopQueries() {
	}

	public TableTopQueries(String querySql, Float elapsedTime,
			String queryTime, Integer queryOrder, TableLogFile log_file) {
		this.querySql = querySql;
		this.elapsedTime = elapsedTime;
		this.queryTime = queryTime;
		this.queryOrder = queryOrder;
		this.logFile = log_file;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getQuerySql() {
		return this.querySql;
	}

	public void setQuerySql(String querySql) {
		this.querySql = querySql;
	}

	public Float getElapsedTime() {
		return this.elapsedTime;
	}

	public void setElapsedTime(Float elapsedTime) {
		this.elapsedTime = elapsedTime;
	}

	public String getQueryTime() {
		return this.queryTime;
	}

	public void setQueryTime(String queryTime) {
		this.queryTime = queryTime;
	}

	public Integer getQueryOrder() {
		return this.queryOrder;
	}

	public void setQueryOrder(Integer queryOrder) {
		this.queryOrder = queryOrder;
	}

	
	public TableLogFile getLogFile(){
		return this.logFile;
	}
	
	public void setLogFile(TableLogFile log_file){
		this.logFile=log_file;
	}


}
