package com.amster.db.hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;


// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableDiag generated by hbm2java
 *
 *
 */

@Entity
@Table(name = "table_diag")
public class TableDiag implements java.io.Serializable {

	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "diag_value")
	private Integer diagValue;
	
	@Column(name = "diag_time")
	private String diagTime;

	@JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "diag2diag_info")
	private TableDiagInfo diagInfo;

	public TableDiag() {
	}

	public TableDiag(Integer diagValue, String diagTime, TableDiagInfo diag_info) {
		this.diagValue = diagValue;
		this.diagTime = diagTime;
		this.diagInfo=diag_info;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDiagValue() {
		return this.diagValue;
	}

	public void setDiagValue(Integer diagValue) {
		this.diagValue = diagValue;
	}

	public String getDiagTime() {
		return this.diagTime;
	}

	public void setDiagTime(String diagTime) {
		this.diagTime = diagTime;
	}

	public TableDiagInfo getDiagInfo(){
		return this.diagInfo;
	}
	
	public void setDiagInfo(TableDiagInfo diag_info){
		this.diagInfo = diag_info;
	}


}
