package com.amster.db.hibernate;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableTimeline generated by hbm2java
 */

@Entity
@Table(name = "table_file_info")
public class TableTimeline implements java.io.Serializable {

	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "timeline_time")
	private String timelineTime;
	
	@Column(name = "timeline_order")
	private Integer timeOrder;
	
	@JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id")
	private TableLogFile logFile;

    @OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "time_log_timeline")
	private Set<TableTimeLog> timeLogs = new HashSet<TableTimeLog>(0);

	public TableTimeline() {
	}

	public TableTimeline(String timelineTime, Integer timeOrder,
			TableLogFile logfile) {
		this.timelineTime = timelineTime;
		this.timeOrder = timeOrder;
		this.logFile= logfile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTimelineTime() {
		return this.timelineTime;
	}

	public void setTimelineTime(String timelineTime) {
		this.timelineTime = timelineTime;
	}

	public Integer getTimeOrder() {
		return this.timeOrder;
	}

	public void setTimeOrder(Integer timeOrder) {
		this.timeOrder = timeOrder;
	}

	public TableLogFile getLogFile(){
		return this.logFile;
	}
	
	public void setLogFile(TableLogFile log_file){
		this.logFile=log_file;
	}

	public Set<TableTimeLog> getTimeLogs() {
		return this.timeLogs;
	}

	public void setTimeLogs(Set<TableTimeLog> timelogs) {
		this.timeLogs=timelogs;
	}
	

}
