package com.amster.db.hibernate;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableThreadFile generated by hbm2java
 */
public class TableThreadFile implements java.io.Serializable {

	private Integer id;
	private String threadId;
	private String threadFile;
	@JsonIgnore
	private TableLogFile logFile;


	public TableThreadFile() {
	}

	public TableThreadFile(String threadId, String threadFile, TableLogFile log_file) {
		this.threadId = threadId;
		this.threadFile = threadFile;
		this.logFile = log_file;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getThreadId() {
		return this.threadId;
	}

	public void setThreadId(String threadId) {
		this.threadId = threadId;
	}

	public String getThreadFile() {
		return this.threadFile;
	}

	public void setThreadFile(String threadFile) {
		this.threadFile = threadFile;
	}

	public TableLogFile getLogFile(){
		return this.logFile;
	}
	
	public void setLogFile(TableLogFile log_file){
		this.logFile=log_file;
	}

}
