package com.amster.db.hibernate;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableDiagInfo generated by hbm2java
 */

@Entity
@Table(name = "table_diag_info")
public class TableDiagInfo implements java.io.Serializable {

	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "diag_name")
	private String diagName;
	
	@Column(name = "high_water_mark")
	private Integer highWaterMark;
	
	@Column(name = "high_water_time")
	private String highWaterTime;
	
	@JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "diag2log_file")
	private TableLogFile logFile;

	@OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "diagInfo")
	private Set<TableDiag> diags = new HashSet<TableDiag>(0);

	public TableDiagInfo() {
	}

	public TableDiagInfo(String diagName, Integer highWaterMark,
			String highWaterTime, TableLogFile log_file) {
		this.diagName = diagName;
		this.highWaterMark = highWaterMark;
		this.highWaterTime = highWaterTime;
		this.logFile = log_file;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDiagName() {
		return this.diagName;
	}

	public void setDiagName(String diagName) {
		this.diagName = diagName;
	}

	public Integer getHighWaterMark() {
		return this.highWaterMark;
	}

	public void setHighWaterMark(Integer highWaterMark) {
		this.highWaterMark = highWaterMark;
	}

	public String getHighWaterTime() {
		return this.highWaterTime;
	}

	public void setHighWaterTime(String highWaterTime) {
		this.highWaterTime = highWaterTime;
	}

	
	public TableLogFile getLogFile(){
		return this.logFile;
	}
	
	public void setLogFile(TableLogFile log_file){
		this.logFile=log_file;
	}
	
	public Set<TableDiag> getDiags() {
		return this.diags;
	}

	public void setDiags(Set<TableDiag> diags) {
		this.diags = diags;
	}

}
