package com.amster.db.hibernate;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableTimeLog generated by hbm2java
 */
public class TableTimeLog implements java.io.Serializable {

	private Integer id;
	private String heading;
	private String description;
	private Date logTime;
	private String timeString;
	private String headingColour;
	


	private String iconColour;

	@JsonIgnore
	private TableLogFile logFile;

	public TableTimeLog() {
	}

	public TableTimeLog(String heading, String description, Date logTime, String timestring,
						String heading_colour, String icon_colour, TableLogFile logfile) {
		this.heading = heading;
		this.description = description;
		this.logTime = logTime;
		this.timeString = timestring;
		this.headingColour = heading_colour;
		this.iconColour = icon_colour;
		this.logFile = logfile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLogTime() {
		return this.logTime;
	}

	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}
	
	public String getTimeString() {
		return this.timeString;
	}

	public void setTimeString(String timestring) {
		this.timeString = timestring;
	}
	
	public String getHeadingColour() {
		return this.headingColour;
	}

	public void setHeadingColour(String headingColour) {
		this.headingColour = headingColour;
	}
	
	public String getIconColour() {
		return this.iconColour;
	}

	public void setIconColour(String colour) {
		this.iconColour = colour;
	}

	public TableLogFile getLogFile(){
		return this.logFile;
	}
	
	public void setLogFile(TableLogFile log_file){
		this.logFile=log_file;
	}

}
