package com.amster.db.hibernate;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;


// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableDiag generated by hbm2java
 */
public class TableDiag implements java.io.Serializable {

	private Integer id;
	private Integer diagValue;
	private String diagTime;
	@JsonIgnore
	private TableDiagInfo diagInfo;

	public TableDiag() {
	}

	public TableDiag(Integer diagValue, String diagTime, TableDiagInfo diag_info) {
		this.diagValue = diagValue;
		this.diagTime = diagTime;
		this.diagInfo=diag_info;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDiagValue() {
		return this.diagValue;
	}

	public void setDiagValue(Integer diagValue) {
		this.diagValue = diagValue;
	}

	public String getDiagTime() {
		return this.diagTime;
	}

	public void setDiagTime(String diagTime) {
		this.diagTime = diagTime;
	}

	public TableDiagInfo getDiagInfo(){
		return this.diagInfo;
	}
	
	public void setDiagInfo(TableDiagInfo diag_info){
		this.diagInfo = diag_info;
	}


}
