package com.amster.db.hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableExceptionTimes generated by hbm2java
 */

@Entity
@Table(name = "table_exception_times")
public class TableExceptionTimes implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "exception_time")
	private String exceptionTime;
	
	@JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "exception_time2exception")
	private TableException exception;

	public TableExceptionTimes() {
	}

	public TableExceptionTimes(String exceptionTime,
			TableException exception) {
		this.exceptionTime = exceptionTime;
		this.exception = exception;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getExceptionTime() {
		return this.exceptionTime;
	}

	public void setExceptionTime(String exceptionTime) {
		this.exceptionTime = exceptionTime;
	}

	public TableException getException(){
		return this.exception;
	}
	
	public void setException(TableException e){
		this.exception=e;
	}

}
