package com.amster.db.hibernate;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * TableLogFile generated by hbm2java
 */
@Entity
@Table(name = "table_log_file")
public class TableLogFile implements java.io.Serializable {

	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "short_name")
	private String shortName;
	
	@Column(name = "real_file_name")
	private String realFileName;
	
	@Column(name = "output_file_name")
	private String outputFileName;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "create_date")
	private Date createDate;
	
    @OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "logFile")
	private Set<TableThreadFile> threadFiles = new HashSet<TableThreadFile>(0);

    @OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "logFile")
	private Set<TableTopQueries> topQueries = new HashSet<TableTopQueries>(0);

    @OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "logFile")
	private Set<TableException> exceptions = new HashSet<TableException>(0);

    @OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "logFile")
	private Set<TableDiagInfo> diagInfo = new HashSet<TableDiagInfo>(0);

    @OneToMany(cascade = CascadeType.ALL , fetch = FetchType.LAZY, mappedBy = "logFile")
	private Set<TableTimeLog> timeLog = new HashSet<TableTimeLog>(0);


	public TableLogFile() {
	}

	public TableLogFile(String shortName, String realFileName, String outputFileName, String description, Date createDate) {
		this.shortName = shortName;
		this.realFileName = realFileName;
		this.outputFileName = outputFileName;
		this.description = description;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getRealFileName() {
		return this.realFileName;
	}

	public void setRealFileName(String realFileName) {
		this.realFileName = realFileName;
	}

	public String getOutputFileName() {
		return this.outputFileName;
	}

	public void setOutputFileName(String outputFileName) {
		this.outputFileName = outputFileName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	public Set<TableThreadFile> getThreadFiles() {
		return this.threadFiles;
	}

	public void setThreadFiles(Set<TableThreadFile> thread_files) {
		this.threadFiles = thread_files;
	}

	public Set<TableTopQueries> getTopQueries() {
		return this.topQueries;
	}

	public void setTopQueries(Set<TableTopQueries> queries) {
		this.topQueries = queries;
	}
	
	public Set<TableException> getExceptions() {
		return this.exceptions;
	}

	public void setExceptions(Set<TableException> es) {
		this.exceptions = es;
	}
	
	public Set<TableDiagInfo> getDiagInfo() {
		return this.diagInfo;
	}

	public void setDiagInfo(Set<TableDiagInfo> diags) {
		this.diagInfo = diags;
	}
	
	public Set<TableTimeLog> getTimeLog() {
		return this.timeLog;
	}

	public void setTimeLog(Set<TableTimeLog> timelog) {
		this.timeLog=timelog;
	}
}
