package com.amster.db.hibernate;


// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableThreadFile generated by hbm2java
 */
public class ViewThreadFile implements java.io.Serializable {

	private Integer id;
	private String threadId;
	private String threadFile;
	private Integer logFile;


	public ViewThreadFile() {
	}

	public ViewThreadFile(String threadId, String threadFile, Integer log_file) {
		this.threadId = threadId;
		this.threadFile = threadFile;
		this.logFile = log_file;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getThreadId() {
		return this.threadId;
	}

	public void setThreadId(String threadId) {
		this.threadId = threadId;
	}

	public String getThreadFile() {
		return this.threadFile;
	}

	public void setThreadFile(String threadFile) {
		this.threadFile = threadFile;
	}

	public Integer getLogFile() {
		return logFile;
	}

	public void setLogFile(Integer logFile) {
		this.logFile = logFile;
	}

}
