package com.amster.db.hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableThreadFile generated by hbm2java
 */

@Entity
@Table(name = "view_thread_file")
public class ViewThreadFile implements java.io.Serializable {

	
	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "thread_id")
	private String threadId;
	
	@Column(name = "thread_file")
	private String threadFile;
	
	@Column(name = "thread_info2log_file")
	private Integer logFile;


	public ViewThreadFile() {
	}

	public ViewThreadFile(String threadId, String threadFile, Integer log_file) {
		this.threadId = threadId;
		this.threadFile = threadFile;
		this.logFile = log_file;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getThreadId() {
		return this.threadId;
	}

	public void setThreadId(String threadId) {
		this.threadId = threadId;
	}

	public String getThreadFile() {
		return this.threadFile;
	}

	public void setThreadFile(String threadFile) {
		this.threadFile = threadFile;
	}

	public Integer getLogFile() {
		return logFile;
	}

	public void setLogFile(Integer logFile) {
		this.logFile = logFile;
	}

}
