package com.amster.db.hibernate;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;


/**
 * TableLogFile generated by hbm2java
 */

@Entity
@Table(name = "view_log_file")
public class ViewLogFile implements java.io.Serializable {

	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "short_name")
	private String shortName;
	
	@Column(name = "real_file_name")
	private String realFileName;
	
	@Column(name = "output_file_name")
	private String outputFileName;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "create_date")
	@Type(type="date")
	private Date createDate;

	

	public ViewLogFile() {
	}

	public ViewLogFile(String shortName, String realFileName,
			String outputFileName, String description, Date createDate) {
		this.shortName = shortName;
		this.realFileName = realFileName;
		this.outputFileName = outputFileName;
		this.description = description;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getRealFileName() {
		return this.realFileName;
	}

	public void setRealFileName(String realFileName) {
		this.realFileName = realFileName;
	}

	public String getOutputFileName() {
		return this.outputFileName;
	}

	public void setOutputFileName(String outputFileName) {
		this.outputFileName = outputFileName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
}	
