package com.amster.db.hibernate;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * TableTimeLog generated by hbm2java
 */

@Entity
@Table(name = "view_time_log")
public class ViewTimeLog implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name = "_id")
	private Integer id;
	
	@Column(name = "heading")
	private String heading;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "log_time")
	private Date logTime;
	
	@Column(name = "time_string")
	private String timeString;
	
	@Column(name = "heading_colour")
	private String headingColour;
	
	@Column(name = "icon_colour")
	private String iconColour;
	
	@Column(name = "time_log2log_file")
	private Integer logFile;
	

	public ViewTimeLog() {
	}

	public ViewTimeLog(String heading, String description, Date logTime, String timestring,
						String heading_colour, String icon_colour, Integer logfile) {
		
		this.heading = heading;
		this.description = description;
		this.logTime = logTime;
		this.timeString = timestring;
		this.headingColour = heading_colour;
		this.iconColour = icon_colour;
		this.logFile = logfile;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getLogTime() {
		return this.logTime;
	}

	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}
	
	public String getTimeString() {
		return this.timeString;
	}

	public void setTimeString(String timestring) {
		this.timeString = timestring;
	}
	
	public String getHeadingColour() {
		return this.headingColour;
	}

	public void setHeadingColour(String headingColour) {
		this.headingColour = headingColour;
	}
	
	public String getIconColour() {
		return this.iconColour;
	}

	public void setIconColour(String colour) {
		this.iconColour = colour;
	}


	public Integer getLogFile() {
		return logFile;
	}

	public void setLogFile(Integer logFile) {
		this.logFile = logFile;
	}

}
