package com.amster.db.hibernate;

// Generated Sep 8, 2016 3:44:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;


/**
 * TableLogFile generated by hbm2java
 */
public class ViewLogFile implements java.io.Serializable {

	private Integer id;
	private String shortName;
	private String realFileName;
	private String outputFileName;
	private String description;
	private Date createDate;
	

	public ViewLogFile() {
	}

	public ViewLogFile(String shortName, String realFileName,
			String outputFileName, String description, Date createDate) {
		this.shortName = shortName;
		this.realFileName = realFileName;
		this.outputFileName = outputFileName;
		this.description = description;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getRealFileName() {
		return this.realFileName;
	}

	public void setRealFileName(String realFileName) {
		this.realFileName = realFileName;
	}

	public String getOutputFileName() {
		return this.outputFileName;
	}

	public void setOutputFileName(String outputFileName) {
		this.outputFileName = outputFileName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
}	
